const String appName = "MedicPulse Doc.";
const String devInfo = 'Developed By AppDev Guys';
const String appTag = "Save Life Mission";
const String verCode = 'v 1.1.0';
const String skip = 'Skip';
const String next = 'Next';
const String googleSignin = 'Sign In With Google';
const String phoneSignIn = 'Sign In With Phone Number';
const String phoneVerification = 'Phone Number Verification';
